{
  "name": "catch-and-match",
  "version": "0.2.14",
  "description": "Assert an error thrown (a)synchronously by a function.",
  "author": "Sam Gluck <sdgluck@gmail.com>",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sdgluck/catch-and-match.git"
  },
  "scripts": {
    "test": "node ./node_modules/mocha/bin/_mocha test",
    "lint": "standard /src/index.js",
    "build": "babel ./src --out-dir ./",
    "prepublish": "npm run -s lint && npm run build && npm run -s test"
  },
  "bugs": {
    "url": "https://github.com/sdgluck/catch-and-match/issues"
  },
  "keywords": [
    "catch",
    "match",
    "try",
    "test",
    "helper",
    "assert",
    "expect"
  ],
  "babel": {
    "presets": [
      "es2015",
      "stage-0"
    ]
  },
  "devDependencies": {
    "babel-cli": "^6.2.0",
    "babel-eslint": "^5.0.0-beta4",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-stage-0": "^6.3.13",
    "mocha": "^2.3.4",
    "standard": "^6.0.5"
  },
  "standard": {
    "parser": "babel-eslint"
  }
}
